name: Push to Docker

on:
    release:
        types: [published]

jobs:
    docker-push:
        runs-on: ubuntu-latest
        env:
            DOCKER_BUILDKIT: 1
            VERSION: ${{github.event.release.tag_name}}

        steps:
            - uses: actions/checkout@v2

            - name: Set version string
              id: vars
              run: echo ::set-output name=release_version::${VERSION##*v}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Build
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64,linux/386
                  push: true
                  tags: |
                      polymathian/sharpei:latest
                      polymathian/sharpei:${{ steps.vars.outputs.release_version }}
